name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: bipul-unexpected

      - name: Commit 3D graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3d contribution graph"
          file_pattern: "profile-3d-contrib/*"
